# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'BeWorth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BeWorth

  target 'BeWorthTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeWorthUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'AFNetworking','3.2.0'

end
