# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'BeWorth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BeWorth

  target 'BeWorthTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeWorthUITests' do
    inherit! :search_paths
    # Pods for testing
  end

source 'https://github.com/CocoaPods/Specs.git'  # 官方库
#source 'https://gitee.com/ZhangLeYi/component_set.git'   #项目库

#pod 'Meditation_model','0.0.1' #业务模块-冥想
#pod 'PodTestLibrary', :podspec => '~/code/Cocoapods/podTest/PodTestLibrary/PodTestLibrary.podspec'  #指定podspec文件

pod 'Meditation_model', :path => '/Users/yaoln/Desktop/AutoProject/Meditation/Meditation_model'      #指定路径
pod 'MainMenu', :path =>’/Users/yaoln/Desktop/AutoProject/MainMenu‘

end
